/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'User' at '25. 3. 24 오후 2:20' with Gradle 2.14.1
 *
 * @author User, @date 25. 3. 24 오후 2:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
